# Generated by Django 5.2.4 on 2025-07-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='date_solved',
            new_name='date_solution',
        ),
    ]
