# Generated by Django 5.2.4 on 2025-07-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_badge_rename_date_solved_solution_date_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c++', 'C++'), ('c#', 'C#'), ('javascript', 'JavaScript'), ('pascal', 'Pascal')], default='python', max_length=20),
        ),
    ]
