# Generated by Django 5.2.4 on 2025-07-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_date_solved_solution_date_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='complexity',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard'), (3, 'Extreme'), (4, 'Hardcore')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bages',
            field=models.ManyToManyField(blank=True, to='app.badge'),
        ),
    ]
