# Generated by Django 5.2.4 on 2025-07-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_badge_alter_task_complexity_userprofile_bages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='color',
            field=models.IntegerField(choices=[(0, 'Green'), (1, 'Blue'), (2, 'Yellow'), (3, 'Purple'), (4, 'Red')]),
        ),
    ]
